name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2
      
      - name: Node compress
        run: zip lambda.zip ./* -r

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      #Upload to S3
      - name: Upload to S3
        run: aws s3 cp ./lambda.zip s3://lambda-functions

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: twitter-demo-stack
          template: stack.yml
          no-fail-on-empty-changeset: "1"