name: 'Deploy to AWS CloudFormation'

on: 
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code from master branch
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Install packages
        run: npm run build

      - name: Install packages for Lambda
        run: cd src/functions && npm install

      - name: Build Lambda
        run: cd src/functions && ls -l && npm run build

      - name: Copy entity to functions
        run: cp -R dist/entity dist-functions/entity
        
      
      - name: Copy migrations to functions
        run: cp -R dist/entity dist-functions/entity

      - name: Copy dependencies
        run: cp -R src/functions/node_modules ./dist-functions/node_modules
      
      - name: Node compress
        run: ls && zip lambda.zip ./dist-functions/* -r

      # Configure AWS Credential
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      #Upload to S3
      - name: Upload to S3
        run: aws s3 cp ./lambda.zip s3://vigneshj-twitter-clone

      # Deploy to AWS CloudFormation
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: twitter-stack
          template: stack.yml
          no-fail-on-empty-changeset: "1"
      - name: Run Migrations
        run: curl -X POST https://jgvp717ay4.execute-api.eu-west-2.amazonaws.com/stage/execute-migration